#!/bin/bash

set -e

#  2000::c0a8:2  a         b
#   H0 \  / R1  ----  R2 \
#     X R0                S 2001::1
#   H1 /  \ R3  ----  R4 /
#  2000::c0a8:3  c         d

ip netns add ns-h0
ip netns add ns-h1
ip netns add ns-r0
ip netns add ns-r1
ip netns add ns-r2
ip netns add ns-r3
ip netns add ns-r4
ip netns add ns-s
ip netns exec ns-r0 sysctl -w net.ipv6.conf.all.forwarding=1
ip netns exec ns-r1 sysctl -w net.ipv6.conf.all.forwarding=1
ip netns exec ns-r2 sysctl -w net.ipv6.conf.all.forwarding=1
ip netns exec ns-r3 sysctl -w net.ipv6.conf.all.forwarding=1
ip netns exec ns-r4 sysctl -w net.ipv6.conf.all.forwarding=1

brctl addbr br-x
brctl addbr br-b

ip l add h0x type veth peer name xh0
ip l add h1x type veth peer name xh1
ip l add r0x type veth peer name xr0
ip l add r0r1 type veth peer name r1r0
ip l add r0r3 type veth peer name r3r0
ip l add r1r2 type veth peer name r2r1
ip l add r3r4 type veth peer name r4r3
ip l add r2b type veth peer name br2
ip l add r4b type veth peer name br4
ip l add sb type veth peer name bs

brctl addif br-x xh0
brctl addif br-x xh1
brctl addif br-x xr0

brctl addif br-b br2
brctl addif br-b br4
brctl addif br-b bs

ip l set h0x netns ns-h0
ip l set h1x netns ns-h1
ip l set r0x netns ns-r0
ip l set r0r1 netns ns-r0
ip l set r0r3 netns ns-r0
ip l set r1r0 netns ns-r1
ip l set r1r2 netns ns-r1
ip l set r2r1 netns ns-r2
ip l set r2b netns ns-r2
ip l set r3r0 netns ns-r3
ip l set r3r4 netns ns-r3
ip l set r4r3 netns ns-r4
ip l set r4b netns ns-r4
ip l set sb netns ns-s

ip l set br-x up
ip l set xh0 up
ip l set xh1 up
ip l set xr0 up

ip l set br-b up
ip l set br2 up
ip l set br4 up
ip l set bs up

ip netns exec ns-h0 ip l set h0x up
ip netns exec ns-h1 ip l set h1x up
ip netns exec ns-r0 ip l set r0x up
ip netns exec ns-r0 ip l set r0r1 up
ip netns exec ns-r0 ip l set r0r3 up
ip netns exec ns-r1 ip l set r1r0 up
ip netns exec ns-r1 ip l set r1r2 up
ip netns exec ns-r2 ip l set r2r1 up
ip netns exec ns-r2 ip l set r2b up
ip netns exec ns-r3 ip l set r3r0 up
ip netns exec ns-r3 ip l set r3r4 up
ip netns exec ns-r4 ip l set r4r3 up
ip netns exec ns-r4 ip l set r4b up
ip netns exec ns-s ip l set sb up

ip netns exec ns-h0 ip a add 2000::c0a8:2/120 dev h0x
ip netns exec ns-h1 ip a add 2000::c0a8:3/120 dev h1x
ip netns exec ns-r0 ip a add 2000::c0a8:1/120 dev r0x
ip netns exec ns-r0 ip a add a::1/64 dev r0r1
ip netns exec ns-r0 ip a add c::1/64 dev r0r3
ip netns exec ns-r1 ip a add a::2/64 dev r1r0
ip netns exec ns-r1 ip a add b::1/64 dev r1r2
ip netns exec ns-r2 ip a add b::2/64 dev r2r1
ip netns exec ns-r2 ip a add dev r2s
ip netns exec ns-r3 ip a add dev r3r0
ip netns exec ns-r3 ip a add dev r3r4
ip netns exec ns-r4 ip a add dev r4r3
ip netns exec ns-r4 ip a add dev r4s
ip netns exec ns-s ip a add dev sr2
ip netns exec ns-s ip a add dev sr4


ip netns exec ns-h0 ip r add b::/64 via a::2
ip netns exec ns-h0 ip r add c::/64 via a::2
ip netns exec ns-h0 ip r add d::/64 via a::2
ip netns exec ns-h0 ip r add e::/64 via a::2

ip netns exec ns-h1 ip r add a::/64 via e::2
ip netns exec ns-h1 ip r add b::/64 via e::2
ip netns exec ns-h1 ip r add c::/64 via e::2
ip netns exec ns-h1 ip r add d::/64 via e::2

ip netns exec ns-r0 ip r add d::/64 via c::2
ip netns exec ns-r0 ip r add e::/64 via b::2

ip netns exec ns-r1 ip r add c::/64 via d::2
ip netns exec ns-r1 ip r add a::/64 via b::1

ip netns exec ns-r2 ip r add a::/64 via c::1
ip netns exec ns-r2 ip r add b::/64 via c::1
ip netns exec ns-r2 ip r add e::/64 via d::1

sleep 3
