#!/bin/bash

ip netns del ns-h0
ip netns del ns-h1
ip netns del ns-r0
ip netns del ns-r1
ip netns del ns-r2


ip l del h0r0
ip l del h1r1
ip l del r0r1
ip l del r0r2
ip l del r1r2

rm /tmp/flsw_test*.log
for m in $__BPFFS_PATH__/*; do
    umount $m
done
sleep 1
rm -rf $__BPFFS_PATH__

exit 0
