#!/bin/bash

set -e
trap 'trap_err $LINENO' ERR

ip netns exec ns-r0 stdbuf -o0 tcpdump -nne -i r0r1 host a::1 and host e::1  &>/tmp/flsw_test.log &
pid=$!
sleep 1
ip netns exec ns-h0 ping -qc 1 e::1 | expect_has '1 received'
sleep 1
kill $pid || :
cat /tmp/flsw_test.log | expect_has 'a::1 > e::1: ICMP6, echo request, seq 1'
cat /tmp/flsw_test.log | expect_has 'e::1 > a::1: ICMP6, echo reply, seq 1'
